[package]
name = "test_1gb_huge_pages"
version = "0.1.0"
authors = ["Noah Mogensen <mogensenn@sou.edu>"]

[dependencies]

[dependencies.memory]
path = "../../kernel/memory"

[dependencies.app_io]
path = "../../kernel/app_io"

# [dependencies.application_main_fn]
# path = "../../compiler_plugins"